---
- name: Install multiple applications
  hosts: localhost
  become: yes
  tasks:
  
    - name: Download and add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  
    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
        state: present
        filename: "hashicorp"

    - name: Update APT package list
      apt:
        update_cache: yes
    
    - name: Install multiple applications with APT
      apt:
        name:
          - snapd
          - git
          - htop
          - python3-pip
          - 7zip
          - ansible
          - postgresql-client-common
          - postgresql-client
          #- virtualbox #notGoodIdeaIfSecurebootisenable
          - vagrant
          #- pcscd
          - opensc-pkcs11
          - opensc
          - pcsc-tools
          - wget
          - libstrongswan-standard-plugins
          - libstrongswan-extra-plugins
          - strongswan-swanctl
          - charon-systemd
          - sshpass
          - net-tools
          - kubectx
          #- firefox-esr
          #- k9s
          - zsh
          #- markdownlint # used by nvim lint but not working still ! maybe because npm not installed ?
          - unzip # required for nvim really ?
          - gcc # required for nvim really ?
          - fontconfig # required for nvim really ?
          - wl-clipboard # required for neovim to system clipboard
          - nodejs # required for LSP yaml-language-server for neovim
          - npm # required for LSP yaml-language-server for neovim
          - rustc # install rust and cargo, required for LSP gitlab-ci-ls for neovim
        state: present



    - name: Install multiple applications with Snap
      snap:
        name:
          - chromium
          - tree
          - bitwarden
          - libreoffice
          - curl
          - k9s
          - joplin-desktop
        state: present

    - name: Install vi snap --classic
      snap:
        name:
          - kubectl
          - helm
        state: present
        classic: yes

# echo 'export PATH=$PATH:/snap/bin' >> ~/.bashrc
# echo 'export PATH=$PATH:/snap/k9s/current/bin' >> ~/.bashrc 
# requires logout / login for debian to see the apps installed then...

    - name: Add kubectl alias to .bash_aliases
      lineinfile:
        path: "/home/fnature/.bash_aliases"
        line: "{{ item }}"
        create: yes
        owner: "fnature"
      loop:
        - "alias kubectl='kubectl'"
        - "alias k='kubectl'"

    - name: Add kubectl alias to .zshrc
      lineinfile:
        path: "/home/fnature/.zshrc"
        line: "{{ item }}"
        create: yes
        owner: "fnature"
      loop:
        - "alias kubectl='kubectl'"
        - "alias k='kubectl'"


    - name: Ensure /etc/environment contains the desired configuration
      copy:
        dest: /etc/environment
        content: |
          PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
          no_proxy=192.168.1.0/24
          NO_PROXY=192.168.1.0/24
          GDK_DPI_SCALE=0.8
        # GDK_DPI_SCALE is to have scale lower on my external monitor
        owner: root
        group: root
        mode: '0644'

# Install from https://github.com/neovim/neovim/releases
# chmod u+x nvim.appimage
# create folder /home/fnature/bin
# mv nvim.appimage /home/fnature/nvim
# echo 'export PATH=$PATH:/home/fnature/bin' >> ~/.bashrc


- name: Install stuffs with non root
  hosts: localhost
  tasks:
  
    - name: Ensure neovim config 
      git:
        repo: "https://github.com/fnature/nvim"
        dest: "/home/fnature/.config/nvim"
        version: main
        update: yes


#MANUAL ONLY
# ---------------------------------------------
# Install nerdfont for neovim
# curl -L https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip --output JetBrainsMono.zip
# sudo unzip JetBrainsMono.zip -d /usr/local/share/fonts
# sudo rm -f JetBrainsMono.zip
# sudo fc-cache -fv
# ca permet d'avoir icons dans neotree

# GNOME Terminal:
# Open Preferences
# Select your profile → Enable Custom Font
# Choose JetBrainsMono Nerd Font
# Ca permet d'avoir les icones dans la status bar dans neovim..

# -------------------------------------------------------
# https://github.com/ohmyzsh/ohmyzsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# then it gets updated automatically


# -------------------------------------------------------
    #- name: Ensure zsh-autosuggestions is cloned and updated
      #git:
        #repo: "https://github.com/zsh-users/zsh-autosuggestions"
        #dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        #version: master
       #update: yes
  

# ------------------------------------------
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
# Add the plugin to the list of plugins for Oh My Zsh to load (inside ~/.zshrc):

# plugins=( 
#     # other plugins...
#     zsh-autosuggestions
# )

# echo 'export PATH=$PATH:/snap/bin' >> ~/.zshrc
# echo 'export PATH=$PATH:/snap/k9s/current/bin' >> ~/.bashrc 
# echo 'export PATH=$PATH:/home/fnature/bin' >> ~/.zshrc
        #
        #
#download https://www.giuspen.net/cherrytree/#downl
# sudo dpkg -i package-name.deb
        # and I coudn't do apt install, I had unmet dependencies..
        # sudo apt --fix-broken install
        #

# ------------------------------------------
# to get airpods pro 2 running
# https://gist.github.com/aidos-dev/b49078c1d8c6bb1621e4ac199d18213b
# sudo nano /etc/bluetooth/main.conf
# set to ControllerMode = dual
# sudo /etc/init.d/bluetooth restart
# micro may not work.. more stuffs to do .. from the same link.... still not very good
