---
- name: Install multiple applications
  hosts: localhost
  become: yes
  tasks:


    # ---------- Docker -------------
    - name: Ensure required packages are installed
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Create keyrings directory (if not exists)
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key (ASCII format)
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /usr/share/keyrings/docker.asc
        mode: '0644'

    - name: Get architecture
      command: dpkg --print-architecture
      register: arch_output
      changed_when: false

    - name: Get distribution codename
      command: bash -c '. /etc/os-release && echo "$VERSION_CODENAME"'
      register: codename_output
      changed_when: false

    - name: Add Docker apt repository (signed-by .asc key)
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ arch_output.stdout }} signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/debian {{ codename_output.stdout }} stable


    # ---------- HashiCorp -------------
    - name: Download and add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  
    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
        state: present
        filename: "hashicorp"
 
    - name: Download and add virtualbox GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  
    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
        state: present
        filename: "hashicorp"

    # ---------- Oracle -------------
    - name: Download and add Oracle VirtualBox GPG key
      ansible.builtin.get_url:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        dest: /tmp/oracle_vbox_2016.asc
        mode: '0644'

    - name: Decrypt and store Oracle VirtualBox GPG key
      ansible.builtin.command:
        cmd: gpg --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg --dearmor /tmp/oracle_vbox_2016.asc
      args:
        creates: /usr/share/keyrings/oracle-virtualbox-2016.gpg

    - name: Add VirtualBox repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib"
        state: present
        filename: "virtualbox"

    # ---------- Apt Update -------------
    - name: Update APT package list
      apt:
        update_cache: yes
    
    # ---------- Install -------------
    - name: Install multiple applications with APT
      apt:
        name:
          - snapd
          - git
          - htop
          - python3-pip
          - 7zip
          - ansible
          - postgresql-client-common
          - postgresql-client
          - virtualbox-7.1
          - vagrant
          #- pcscd
          - opensc-pkcs11
          - opensc
          - pcsc-tools
          - wget
          - libstrongswan-standard-plugins
          - libstrongswan-extra-plugins
          - strongswan-swanctl
          - charon-systemd
          - sshpass
          - net-tools
          - kubectx
          #- firefox-esr
          #- k9s
          - zsh
          #- markdownlint # used by nvim lint but not working still ! maybe because npm not installed ?
          - unzip # required for nvim really ?
          - gcc # required for nvim really ?
          - fontconfig # required for nvim really ?
          - wl-clipboard # required for neovim to system clipboard
          - nodejs # required for LSP yaml-language-server for neovim
          - npm # required for LSP yaml-language-server for neovim
          - rustc # install rust and cargo, required for LSP gitlab-ci-ls for neovim
          - ripgrep # faster than grep and required for neovim ctrlsf plugin
          # - go # required for neovim lsp gitlab-ci-ls NOT WORKING
          - maven
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - obs-studio
          - filezilla
        state: present



    - name: Install multiple applications with Snap
      snap:
        name:
          - chromium
          - tree
          - bitwarden
          - libreoffice
          - k9s
          - joplin-desktop
        state: present

    - name: Install vi snap --classic
      snap:
        name:
          - kubectl
          - helm
          - shotcut
        state: present
        classic: yes

# echo 'export PATH=$PATH:/snap/bin' >> ~/.bashrc
# echo 'export PATH=$PATH:/snap/k9s/current/bin' >> ~/.bashrc 
# requires logout / login for debian to see the apps installed then...

    - name: Add kubectl alias to .bash_aliases
      lineinfile:
        path: "/home/fnature/.bash_aliases"
        line: "{{ item }}"
        create: yes
        owner: "fnature"
      loop:
        - "alias kubectl='kubectl'"
        - "alias k='kubectl'"

    - name: Add kubectl alias to .zshrc
      lineinfile:
        path: "/home/fnature/.zshrc"
        line: "{{ item }}"
        create: yes
        owner: "fnature"
      loop:
        - "alias kubectl='kubectl'"
        - "alias k='kubectl'"


    - name: Ensure /etc/environment contains the desired configuration
      copy:
        dest: /etc/environment
        content: |
          PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
          no_proxy=192.168.1.0/24
          NO_PROXY=192.168.1.0/24
          GDK_DPI_SCALE=0.8
        # GDK_DPI_SCALE is to have scale lower on my external monitor
        owner: root
        group: root
        mode: '0644'

# Install from https://github.com/neovim/neovim/releases
# chmod u+x nvim.appimage
# create folder /home/fnature/bin
# mv nvim.appimage /home/fnature/nvim
# echo 'export PATH=$PATH:/home/fnature/bin' >> ~/.bashrc

# ------------------------------------------
# Homebrew update
    - name: Create Homebrew auto-update cron job
      copy:
        dest: /etc/cron.d/homebrew-cronjob
        content: |
          # This cron job will run every Monday at 10:00 AM
          0 10 * * 1 root /opt/homebrew/bin/brew update && /opt/homebrew/bin/brew upgrade && /opt/homebrew/bin/brew cleanup
        owner: root
        group: root
        mode: '0644'


# ------------------DIFFERENT ANSIBLE PLAY------------------------
- name: Install stuffs with non root
  hosts: localhost
  tasks:
  
    - name: Ensure neovim config 
      git:
        repo: "https://github.com/fnature/nvim"
        dest: "/home/fnature/.config/nvim"
        version: main
        update: yes

    - name: Ensure brew shellenv is added to .zshrc
      lineinfile:
        path: /home/{{ ansible_user }}/.zshrc
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
        state: present
        create: yes
      become: false

    - name: Ensure glab is installed with Homebrew
      homebrew:
        name:
          - glab
          - argocd-autopilot
        state: present

# ---------------MANUAL ONLY------------------------------
# Homebrew install
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# Following the install there were other stuffs to add like the eval of the brew shellenv. I don't remember the others !

# -------------------------------------------------------
# Install nerdfont for neovim
# curl -L https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip --output JetBrainsMono.zip
# sudo unzip JetBrainsMono.zip -d /usr/local/share/fonts
# sudo rm -f JetBrainsMono.zip
# sudo fc-cache -fv
# ca permet d'avoir icons dans neotree

# GNOME Terminal:
# Open Preferences
# Select your profile → Enable Custom Font
# Choose JetBrainsMono Nerd Font
# Ca permet d'avoir les icones dans la status bar dans neovim..

# -------------------------------------------------------
# https://github.com/ohmyzsh/ohmyzsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# then it gets updated automatically


# -------------------------------------------------------
    #- name: Ensure zsh-autosuggestions is cloned and updated
      #git:
        #repo: "https://github.com/zsh-users/zsh-autosuggestions"
        #dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        #version: master
       #update: yes
  

# ------------------------------------------
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
# Add the plugin to the list of plugins for Oh My Zsh to load (inside ~/.zshrc):

# plugins=( 
#     # other plugins...
#     zsh-autosuggestions
# )

# echo 'export PATH=$PATH:/snap/bin' >> ~/.zshrc
# echo 'export PATH=$PATH:/snap/k9s/current/bin' >> ~/.bashrc 
# echo 'export PATH=$PATH:/home/fnature/bin' >> ~/.zshrc
        #
        #
#download https://www.giuspen.net/cherrytree/#downl
# sudo dpkg -i package-name.deb
        # and I coudn't do apt install, I had unmet dependencies..
        # sudo apt --fix-broken install
        #

# ------------------------------------------
# to get airpods pro 2 running
# https://gist.github.com/aidos-dev/b49078c1d8c6bb1621e4ac199d18213b
# sudo nano /etc/bluetooth/main.conf
# set to ControllerMode = dual
# sudo /etc/init.d/bluetooth restart
# micro may not work.. more stuffs to do .. from the same link.... still not very good
# ------------------------------------------
# flux
# https://fluxcd.io/flux/installation/#install-the-flux-cli
# curl -s https://fluxcd.io/install.sh | sudo bash
# mkdir -p ~/.oh-my-zsh/completions
# flux completion zsh > ~/.oh-my-zsh/completions/_flux # sufficient for flux completion to work in oh my zsh
# ------------------------------------------
# cat /etc/environment
# PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
# GDK_DPI_SCALE=0.8
# http_proxy=http://direct1.proxy.i2:8080
# https_proxy=http://direct1.proxy.i2:8080
# no_proxy=localhost,127.0.0.1,::1,192.168.0.0/16,10.0.0.0/8
# ------------------------------------------
